export const QUEST_POOL = [
  { id: 'pushup', title: 'PUSH-UP', baseTarget: 10, unit: 'x', icon: 'fitness_center', statType: 'str', description: 'Turunkan badan dengan menekuk siku, lalu dorong kembali ke atas.' },
  { id: 'situp', title: 'SIT-UP', baseTarget: 15, unit: 'x', icon: 'accessibility_new', statType: 'vit', description: 'Berbaring telentang, tekuk lutut, lalu angkat tubuh bagian atas ke arah lutut.' },
  { id: 'squat', title: 'SQUAT', baseTarget: 20, unit: 'x', icon: 'sports_gymnastics', statType: 'str', description: 'Berdiri tegak, turunkan pinggul seperti akan duduk di kursi, lalu berdiri kembali.' },
  { id: 'plank', title: 'PLANK', baseTarget: 30, unit: 'detik', icon: 'accessibility', statType: 'vit', description: 'Tahan tubuh dalam posisi push-up menggunakan lengan bawah. Jaga punggung tetap lurus.' },
  { id: 'run_inplace', title: 'LARI DI TEMPAT', baseTarget: 60, unit: 'detik', icon: 'directions_run', statType: 'agi', description: 'Lari di tempat dengan ritme stabil.' },
  { id: 'jumping_jacks', title: 'JUMPING JACKS', baseTarget: 30, unit: 'x', icon: 'accessibility_new', statType: 'agi', description: 'Lompat sambil membuka kaki dan menepuk tangan di atas kepala.' },
  { id: 'lunges', title: 'LUNGES', baseTarget: 10, unit: 'x', icon: 'sports_gymnastics', statType: 'str', description: 'Langkahkan satu kaki ke depan dan tekuk kedua lutut hingga 90 derajat.' },
  { id: 'burpees', title: 'BURPEES', baseTarget: 5, unit: 'x', icon: 'fitness_center', statType: 'agi', description: 'Dari berdiri, turun ke push-up, lompat kaki ke depan, lalu berdiri dan melompat.' },
  { id: 'high_knees', title: 'HIGH KNEES', baseTarget: 30, unit: 'detik', icon: 'directions_run', statType: 'agi', description: 'Lari di tempat sambil mengangkat lutut setinggi mungkin ke arah dada.' },
  { id: 'wall_sit', title: 'WALL SIT', baseTarget: 30, unit: 'detik', icon: 'accessibility', statType: 'vit', description: 'Sandarkan punggung ke dinding, turunkan pinggul seolah duduk di kursi transparan.' },
  { id: 'crunch', title: 'CRUNCH', baseTarget: 20, unit: 'x', icon: 'accessibility_new', statType: 'vit', description: 'Angkat bahu dari lantai menggunakan otot perut, tanpa mengangkat punggung bawah.' },
  { id: 'mountain_climbers', title: 'MOUNTAIN CLIMBERS', baseTarget: 20, unit: 'x', icon: 'directions_run', statType: 'agi', description: 'Dari posisi push-up, tarik lutut bergantian ke arah dada dengan cepat.' },
  { id: 'russian_twist', title: 'RUSSIAN TWIST', baseTarget: 20, unit: 'x', icon: 'accessibility_new', statType: 'vit', description: 'Duduk dengan kaki sedikit diangkat, putar tubuh bagian atas ke kiri dan kanan.' },
  { id: 'glute_bridge', title: 'GLUTE BRIDGE', baseTarget: 15, unit: 'x', icon: 'accessibility', statType: 'vit', description: 'Berbaring, tekuk lutut, lalu angkat panggul hingga membentuk garis lurus.' },
  { id: 'leg_raises', title: 'LEG RAISES', baseTarget: 10, unit: 'x', icon: 'accessibility_new', statType: 'vit', description: 'Berbaring telentang, jaga kaki lurus, lalu angkat ke atas hingga 90 derajat.' },
  { id: 'bicycle_crunches', title: 'BICYCLE CRUNCHES', baseTarget: 20, unit: 'x', icon: 'directions_bike', statType: 'vit', description: 'Gerakan mengayuh sepeda sambil menyentuhkan siku ke lutut yang berlawanan.' },
  { id: 'calf_raises', title: 'CALF RAISES', baseTarget: 30, unit: 'x', icon: 'sports_gymnastics', statType: 'agi', description: 'Berdiri tegak, jinjit setinggi mungkin, lalu turun perlahan.' },
  { id: 'wall_pushups', title: 'WALL PUSH-UPS', baseTarget: 15, unit: 'x', icon: 'fitness_center', statType: 'str', description: 'Lakukan gerakan push-up sambil berdiri bersandar pada dinding.' },
  { id: 'tricep_dips', title: 'TRICEP DIPS', baseTarget: 10, unit: 'x', icon: 'fitness_center', statType: 'str', description: 'Gunakan kursi, turunkan tubuh menggunakan lengan lalu dorong kembali ke atas.' },
  { id: 'arm_circles', title: 'ARM CIRCLES', baseTarget: 30, unit: 'detik', icon: 'accessibility_new', statType: 'str', description: 'Rentangkan lengan ke samping lalu putar perlahan membentuk lingkaran.' },
  { id: 'shadow_boxing', title: 'SHADOW BOXING', baseTarget: 60, unit: 'detik', icon: 'sports_mma', statType: 'per', description: 'Lakukan gerakan meninju ke udara seperti sedang bertarung.' },
  { id: 'donkey_kicks', title: 'DONKEY KICKS', baseTarget: 15, unit: 'x', icon: 'sports_gymnastics', statType: 'str', description: 'Posisi merangkak, angkat satu kaki ke belakang dan ke atas bergantian.' },
  { id: 'bird_dog', title: 'BIRD DOG', baseTarget: 10, unit: 'x', icon: 'accessibility', statType: 'per', description: 'Merangkak, luruskan lengan kanan dan kaki kiri secara bersamaan.' },
  { id: 'superman', title: 'SUPERMAN HOLD', baseTarget: 20, unit: 'detik', icon: 'accessibility_new', statType: 'str', description: 'Tengkurap, angkat lengan, dada, dan kaki secara bersamaan dan tahan.' },
  { id: 'inchworms', title: 'INCHWORMS', baseTarget: 5, unit: 'x', icon: 'sports_gymnastics', statType: 'str', description: 'Berdiri, sentuh lantai lalu berjalan dengan tangan hingga posisi push-up.' },
  { id: 'flutter_kicks', title: 'FLUTTER KICKS', baseTarget: 20, unit: 'detik', icon: 'accessibility_new', statType: 'agi', description: 'Berbaring, angkat kaki sedikit dan tendang secara bergantian dengan cepat.' },
  { id: 'side_plank', title: 'SIDE PLANK', baseTarget: 20, unit: 'detik', icon: 'accessibility', statType: 'vit', description: 'Bertumpu pada satu lengan bawah dan sisi kaki, angkat pinggul tubuh.' },
  { id: 'butt_kicks', title: 'BUTT KICKS', baseTarget: 30, unit: 'detik', icon: 'directions_run', statType: 'agi', description: 'Lari di tempat sambil menendang tumit ke arah bokong secara bergantian.' }
]
