export const QUEST_POOL = [
  { id: 'pushup', title: 'PUSH-UP', baseTarget: 10, unit: 'x', icon: 'fitness_center', statType: 'str' },
  { id: 'situp', title: 'SIT-UP', baseTarget: 15, unit: 'x', icon: 'accessibility_new', statType: 'vit' },
  { id: 'squat', title: 'SQUAT', baseTarget: 20, unit: 'x', icon: 'sports_gymnastics', statType: 'str' },
  { id: 'plank', title: 'PLANK', baseTarget: 30, unit: 'detik', icon: 'accessibility', statType: 'vit' },
  { id: 'run_inplace', title: 'LARI DI TEMPAT', baseTarget: 60, unit: 'detik', icon: 'directions_run', statType: 'agi' },
  { id: 'jumping_jacks', title: 'JUMPING JACKS', baseTarget: 30, unit: 'x', icon: 'accessibility_new', statType: 'agi' },
  { id: 'lunges', title: 'LUNGES', baseTarget: 10, unit: 'x', icon: 'sports_gymnastics', statType: 'str' },
  { id: 'burpees', title: 'BURPEES', baseTarget: 5, unit: 'x', icon: 'fitness_center', statType: 'agi' },
  { id: 'high_knees', title: 'HIGH KNEES', baseTarget: 30, unit: 'detik', icon: 'directions_run', statType: 'agi' },
  { id: 'wall_sit', title: 'WALL SIT', baseTarget: 30, unit: 'detik', icon: 'accessibility', statType: 'vit' },
  { id: 'crunch', title: 'CRUNCH', baseTarget: 20, unit: 'x', icon: 'accessibility_new', statType: 'vit' },
  { id: 'mountain_climbers', title: 'MOUNTAIN CLIMBERS', baseTarget: 20, unit: 'x', icon: 'directions_run', statType: 'agi' },
  { id: 'russian_twist', title: 'RUSSIAN TWIST', baseTarget: 20, unit: 'x', icon: 'accessibility_new', statType: 'vit' },
  { id: 'glute_bridge', title: 'GLUTE BRIDGE', baseTarget: 15, unit: 'x', icon: 'accessibility', statType: 'vit' },
  { id: 'leg_raises', title: 'LEG RAISES', baseTarget: 10, unit: 'x', icon: 'accessibility_new', statType: 'vit' },
  { id: 'bicycle_crunches', title: 'BICYCLE CRUNCHES', baseTarget: 20, unit: 'x', icon: 'directions_bike', statType: 'vit' },
  { id: 'calf_raises', title: 'CALF RAISES', baseTarget: 30, unit: 'x', icon: 'sports_gymnastics', statType: 'agi' },
  { id: 'wall_pushups', title: 'WALL PUSH-UPS', baseTarget: 15, unit: 'x', icon: 'fitness_center', statType: 'str' },
  { id: 'tricep_dips', title: 'TRICEP DIPS', baseTarget: 10, unit: 'x', icon: 'fitness_center', statType: 'str' },
  { id: 'arm_circles', title: 'ARM CIRCLES', baseTarget: 30, unit: 'detik', icon: 'accessibility_new', statType: 'str' },
  { id: 'shadow_boxing', title: 'SHADOW BOXING', baseTarget: 60, unit: 'detik', icon: 'sports_mma', statType: 'per' },
  { id: 'donkey_kicks', title: 'DONKEY KICKS', baseTarget: 15, unit: 'x', icon: 'sports_gymnastics', statType: 'str' },
  { id: 'bird_dog', title: 'BIRD DOG', baseTarget: 10, unit: 'x', icon: 'accessibility', statType: 'per' },
  { id: 'superman', title: 'SUPERMAN HOLD', baseTarget: 20, unit: 'detik', icon: 'accessibility_new', statType: 'str' },
  { id: 'inchworms', title: 'INCHWORMS', baseTarget: 5, unit: 'x', icon: 'sports_gymnastics', statType: 'str' },
  { id: 'flutter_kicks', title: 'FLUTTER KICKS', baseTarget: 20, unit: 'detik', icon: 'accessibility_new', statType: 'agi' },
  { id: 'side_plank', title: 'SIDE PLANK', baseTarget: 20, unit: 'detik', icon: 'accessibility', statType: 'vit' },
  { id: 'butt_kicks', title: 'BUTT KICKS', baseTarget: 30, unit: 'detik', icon: 'directions_run', statType: 'agi' }
]
